export const FETCH_DATA_REQUEST = "FETCH_DATA_REQUEST"
export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS"
export const FETCH_DATA_FAILURE= "FETCH_DATA_FAILURE"

export const GET_SINGLE_PRODUCT_REQUEST="GET_SINGLE_PRODUCT_REQUEST"
export const GET_SINGLE_PRODUCT_SUCCESS="GET_SINGLE_PRODUCT_SUCCESS"
export const GET_SINGLE_PRODUCT_FAILURE="GET_SINGLE_PRODUCT_FAILURE"


export const ADD_PRODUCT_CART_REQUEST= "ADD_PRODUCT_CART_REQUEST"
export const ADD_PRODUCT_CART_SUCCESS= "ADD_PRODUCT_CART_SUCCESS"
export const ADD_PRODUCT_CART_FAILURE="ADD_PRODUCT_CART_FAILURE"


export const FETCH_CART_REQUEST= "FETCH_CART_REQUEST"
export const FETCH_CART_SUCCESS= "FETCH_CART_SUCCESS"
export const FETCH_CART_FAILURE="FETCH_CART_FAILURE"



export const DELETE_CART_REQUEST= "DELETE_CART_REQUEST"
export const DELETE_CART_SUCCESS= "DELETE_CART_SUCCESS"
export const DELETE_CART_FAILURE="DELETE_CART_FAILURE"


export const POST_ORDER_REQUEST= "POST_ORDER_REQUEST"
export const POST_ORDER_SUCCESS= "POST_ORDER_SUCCESS"
export const POST_ORDER_FAILURE="POST_ORDER_FAILURE"




export const FETCH_ORDER_DATA_REQUEST = "FETCH_ORDER_DATA_REQUEST"
export const FETCH_ORDER_DATA_SUCCESS = "FETCH_ORDER_DATA_SUCCESS"
export const FETCH_ORDER_DATA_FAILURE= "FETCH_ORDER_DATA_FAILURE"




